// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package classifier

type File struct {
	ID       int32
	FolderID int32
	Location string
}

type Folder struct {
	ID     int32
	ChatID interface{}
	Name   string
}
